# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: README.md Generator

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Generate README.md and push changes
      run: |
        swift Script/on_merge.swift > README.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generated README.md based on new entry"
        git push
